/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./utils/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("daisyui")],
  darkTheme: "dark",
  darkMode: ["selector", "[data-theme='dark']"],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#915BF8",
          "primary-content": "#ffffff",
          secondary: "#3D1EFE",
          "secondary-content": "#ffffff",
          accent: "#DED1FA",
          "accent-content": "#060713",
          neutral: "#060713",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#DED1FA",
          "base-300": "#BDA0F6",
          "base-content": "#060713",
          info: "#8B8AFF",
          success: "#34EEB6",
          warning: "#FFCF72",
          error: "#FF8863",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
          ".btn": { color: "#ffffff" },
        },
      },
      {
        dark: {
          primary: "#915BF8",
          "primary-content": "#F9FBFF",
          secondary: "#3D1EFE",
          "secondary-content": "#F9FBFF",
          accent: "#7235E5",
          "accent-content": "#F9FBFF",
          neutral: "#F9FBFF",
          "neutral-content": "#121645",
          "base-100": "#121645",
          "base-200": "#060713",
          "base-300": "#060713",
          "base-content": "#F9FBFF",
          info: "#6851FF",
          success: "#34EEB6",
          warning: "#FFCF72",
          error: "#FF8863",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "oklch(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
    ],
  },
  theme: {
    extend: {
      boxShadow: { center: "0 0 12px -2px rgb(0 0 0 / 0.05)" },
      animation: { "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite" },
      colors: {
        primary: {
          DEFAULT: "#915BF8",
          light: "#DED1FA",
          medium: "#BDA0F6",
          dark: "#7235E5",
          darkest: "#551FBC",
        },
        secondary: {
          DEFAULT: "#3D1EFE",
          light: "#8B8AFF",
          medium: "#6851FF",
          dark: "#3118D6",
          darkest: "#2511AE",
        },
        background: {
          malibu: "#8B8AFF",
          navy: "#121645",
          dark: "#060713",
        },
      },
    },
  },
};
